### ISSUE TITLE
Demo Page

### ISSUE THREAD

**Issue by craigcoles** [Hiswe/gulp-svg-symbols#17]
I hate to be that guy...

If you could go ahead and make the demo page more helpful, that would be great

![](http://thisisinfamous.com/wp-content/uploads/2015/03/office-space-gary-cole-bill-lumbergh-480x240.jpg)

Comparing the demo page to that of its predecessor (https://www.npmjs.com/package/gulp-svg-sprites), it is missing the vital ingredient, the code for the SVG icon that needs to be used, for ease of use purposes.

**Comment by lukewhitehouse** [comment]
+1 :)

**Comment by Hiswe** [comment]
:)

Ok I'll try to this during this week (I hope)
To be sure that this subject goes fast, feel free to make a PR about this [file](https://github.com/Hiswe/gulp-svg-symbols/blob/master/templates/svg-symbols-demo-page.html) :P

**Comment by Hiswe** [comment]
@craigcoles @lukewhitehouse It should be ok :)
