### ISSUE TITLE
preserveAspectRatio

### ISSUE THREAD

**Issue by stephanedemotte** [Hiswe/gulp-svg-symbols#18]
Hi,

Thanks for your great plugin !

Small question, how i can keep the preserveAspectRatio="none" attribute ?

I try with svgo : 
```
removeAttrs: false,
removeUnknownsAndDefaults: false,
```

But i can't keep this value.

Any idea ?

**Comment by Hiswe** [comment]
Right now no :(

You can try to play with my still (!!) unfinished branch: https://github.com/Hiswe/gulp-svg-symbols/tree/svgo-removal that doesn't use SVGO :)

It seems to have fixed some problems like in [#6](https://github.com/Hiswe/gulp-svg-symbols/issues/6)

**Comment by Hiswe** [comment]
@stephanedemotte this plugin no longer use SVGO. Everything should be preserved!

**Comment by stephanedemotte** [comment]
great thanks !

**Comment by Hiswe** [comment]
@stephanedemotte you're welcome :)

**Comment by am3000** [comment]
Hey, I also want to keep the preserveAspectRatio attribute of the original svg.
How can I achieve that?
Thanks!

**Comment by Hiswe** [comment]
@am3000 it should be possible to do this with a [custom templates](https://github.com/Hiswe/gulp-svg-symbols#templates) with a [custom transformdata](https://github.com/Hiswe/gulp-svg-symbols#transformdata) function.

**Comment by Hiswe** [comment]
@am3000 a template could look like that

```html
<svg xmlns="http://www.w3.org/2000/svg" style="width:0; height:0; visibility:hidden;"><% if(defs) {%>
  <defs>
      <%= defs %>
  </defs><% } %><% _.forEach( icons, function( icon ){ %>
    <symbol id="<%= icon.id %>" viewBox="<%= icon.svg.viewBox %>"<% if (icon.svg.originalAttributes.preserveAspectRatio) {%> preserveAspectRatio="<%= icon.svg.originalAttributes.preserveAspectRatio %>" <% }%>><% if (icon.title) {%>
      <title><%= icon.title %></title><% }%>
      <%= icon.svg.content %>
    </symbol><%
}); %></svg>
```
But I think I will port it to the default template
