### ISSUE TITLE
Remove style attributes on default SVG template

### ISSUE THREAD

**Issue by Hiswe** [Hiswe/gulp-svg-symbols#25]
as mentioned [here](https://github.com/Hiswe/gulp-svg-symbols/issues/23#issuecomment-162777369) putting a style like:
```html
style="width:0; height:0; visibility:hidden;"
```
is not very helpfull.

Even more when you reference the SVG externally, like:

```html
<svg role="img" class="icon icon-pouic">
  <use xlink:href="/svg/svg-symbols.svg#icon-pouic"></use>
</svg>
```

It should be:

- removed from [SVG template](https://raw.githubusercontent.com/Hiswe/gulp-svg-symbols/master/templates/svg-symbols.svg)
- add in the doc the “hidden accessible” CSS (like in #23)

**Comment by artem-malko** [comment]
And it  will be really useful, if we can set uniq className to main SVG to apply styles only for that SVG.

**Comment by Hiswe** [comment]
@artem-malko I can provide a `name` option for this.
Wouldn't it be more logical to add an `id` instead of a `class`?
Also with providing a name, I can also rename the output files (instead of using `gulp-rename`).

**Comment by artem-malko** [comment]
I mean that we need to apply styles only for root SVG-element, so we need a claasname for it. Id is not good idea, cause some developers prefer only classnames.

**Comment by kencrocken** [comment]
Why not use a custom template?

```js
// custom-template.svg
<svg xmlns="http://www.w3.org/2000/svg" class="your-custom-class"><% if(defs) {%>
  <defs>
      <%= defs %>
  </defs><% } %><% _.forEach( icons, function( icon ){ %>
    <symbol id="<%= icon.id %>" viewBox="<%= icon.svg.viewBox %>"><% if (icon.title) {%>
      <title><%= icon.title %></title><% }%>
      <%= icon.svg.content %>
    </symbol><%
}); %></svg>

// In gulp task
...
.pipe($.svgSymbols({
        id:      'icon-%f',
        className:  '.icon-%f',
        title:      false,
        fontSize:   32,
        templates: [ path.join(__dirname, 'custom-template.svg'),'default-demo' ]
    })
...
```
see [here](https://github.com/Hiswe/gulp-svg-symbols#templates)

**Comment by Hiswe** [comment]
fixed here: https://github.com/Hiswe/gulp-svg-symbols/commit/38b2dcde2621ef94e6c39685a7cc084db04db125

**Comment by sensaetions** [comment]
Hello,
I'm trying to write a custom template for generating svg symbols. I have it written as so:

// custom template.svg
```xml
<svg xmlns="http://www.w3.org/2000/svg"<% if(svgClassname) {%> class="<%= svgClassname %>"<% } %>><% if(defs) {%>
  <defs>
      <%= defs %>
  </defs><% } %><% _.forEach( icons, function( icon ){ %>
<symbol id="<%= icon.id %>" viewBox="<%= icon.svg.viewBox %>" aria-labeledby="<%= icon.title %>"
  <% if (icon.svg.originalAttributes.preserveAspectRatio) {%> preserveAspectRatio="
  <%= icon.svg.originalAttributes.preserveAspectRatio %>"
    <% }%>>
      <% if (icon.title) {%>
      <title><%= icon.title %></title><% }%>
      <%= icon.svg.content %>
    </symbol><%
}); %></svg>
```

I understand I need to set up the path to my custom template. But in my gulp file, the framework I'm using places all npm modules into a constant of `$`. So how would I write the path to join my template files in my gulp task?

// in gulp task
```js
...
.pipe($.svgSymbols({
        id:      'icon-%f',
        className:  '.icon-%f',
        templates: [ $path.join(__dirname, 'custom-template.svg'),'default-css' ]
    })
...
```

**Comment by Hiswe** [comment]
@sensaetions what kind framework are you using?

Have you tried a regular import?

```javascript
const path = require('path');
const templatePath = path.join(__dirname, './custom-template.svg');
```

**Comment by sensaetions** [comment]
@Hiswe, I am using Zurb's Foundation framework, the latest version 6.4.

This framework loads all gulp plugins into one variable, which uses `gulp-load-plugins` to do so.
```javascript
const $ = plugins();
```

**Comment by Hiswe** [comment]
@sensaetions you can keep using `gulp-load-plugins`

Just keep in mind that it will just just [load gulp plugins](https://www.npmjs.com/package/gulp-load-plugins)
the [path](https://nodejs.org/dist/latest-v8.x/docs/api/path.html) module isn't one of them.

so just make a regular import.

```js
const path = require("path");
const gulp = require("gulp");
const gulpLoadPlugins = require("gulp-load-plugins");
const $ = gulpLoadPlugins();

function bundleIcons() {
  return gulp
    .src(`icons/*.svg`)
    .pipe(
      $.svgSymbols({
        templates: [path.join(__dirname, `./custom-template.svg`)]
      })
    )
    .pipe(gulp.dest("dist"));
}
```

```

**Comment by sensaetions** [comment]
Thank you @Hiswe,

I was first using `gulp-path`, but that didn't work. So after installing regular `path` and making a regular import, that solved my issue!

**Comment by Hiswe** [comment]
Yep, using native modules is often a good idea :)
