### ISSUE TITLE
CSS styles stay inside SVGs

### ISSUE THREAD

**Issue by sensaetions** [Hiswe/gulp-svg-symbols#27]
Hello, would it be possible for the css styles to remain in the SVG file, instead of generating a separate `.css` file?

If this is already possible, how can I achieve it?

**Comment by Hiswe** [comment]
Hi @sensaetions,

It's possible to do it by doing a [custom template](https://github.com/Hiswe/gulp-svg-symbols#templates).
I think you can take the [demo template](https://github.com/Hiswe/gulp-svg-symbols/blob/master/templates/svg-symbols-demo-page.html) as a start to achieve what you want :)
