### ISSUE TITLE
Background Image usage?

### ISSUE THREAD

**Issue by shornuk** [Hiswe/gulp-svg-symbols#32]
I'm using this successfully to add svg's inline in my html. Works great. What I can't quite figure out is.. Is there a way I can use the outputted sprite to create a background images?
I.e my search field has a search icon within the input. Rather than adding this inline in the html I'd like to set it as a background image of the input. 
Not sure if this is possible!?

**Comment by Hiswe** [comment]
@shornuk As far as I know It's impossible to call a SVG symbol from a CSS.

What I usually do, if I need, is to call the original file directly… But you can't style it anymore :)
