### ISSUE TITLE
defs section breaks output file because of missing xlink namespace and duplicated IDs

### ISSUE THREAD

**Issue by bluemoehre** [Hiswe/gulp-svg-symbols#34]
If I have source files using `<use xlink:href="..."/>` the output file gets corrupted. It is missing the xlink namespace. Alternatively the `xlink:href` should be converted into `href` which is supported in modern browsers.

e.g. the [European Flag](https://upload.wikimedia.org/wikipedia/commons/b/b7/Flag_of_Europe.svg):

```
<svg xmlns="http://www.w3.org/2000/svg" width="810" height="540" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 810 540">
    <defs>
        <g id="d">
            <g id="b">
                <path id="a" d="M0-1l-.31.95.477.156z"/>
                <use xlink:href="#a" transform="scale(-1 1)"/>
            </g>
            <g id="c">
                <use xlink:href="#b" transform="rotate(72)"/>
                <use xlink:href="#b" transform="rotate(144)"/>
            </g>
            <use xlink:href="#c" transform="scale(-1 1)"/>
        </g>
    </defs>
    <path fill="#039" d="M0 0h810v540H0z"/>
    <g fill="#fc0" transform="matrix(30 0 0 30 405 270)">
        <use y="-6" xlink:href="#d"/>
        <use y="6" xlink:href="#d"/>
        <g id="e">
            <use x="-6" xlink:href="#d"/>
            <use xlink:href="#d" transform="rotate(-144 -2.344 -2.11)"/>
            <use xlink:href="#d" transform="rotate(144 -2.11 -2.344)"/>
            <use xlink:href="#d" transform="rotate(72 -4.663 -2.076)"/>
            <use xlink:href="#d" transform="rotate(72 -5.076 .534)"/>
        </g>
        <use xlink:href="#e" transform="scale(-1 1)"/>
    </g>
</svg>
```

Resulted in a :
`<svg xmlns="http://www.w3.org/2000/svg">` [1] _missing namespace xlink_ error

Additionally the referenced IDs within the `defs` section are not rewritten/renumbered. So if multiple files contain the same ID it will also break the output file:

```
<defs>
  <g id="a"><path d="M0-1l-.31.95.477.156z"/></g>
  <g id="a"><rect width="5" height="1" y="2" x="0"/></g>
</defs>
```

**Comment by Hiswe** [comment]
Hi,

thanks for this report :)

For the missing `xmlns:xlink="http://www.w3.org/1999/xlink"` you can add a [custom template](https://github.com/Hiswe/gulp-svg-symbols#templates-1) with the name space as a temporary solution. [svg-symbols.svg](https://raw.githubusercontent.com/Hiswe/gulp-svg-symbols/master/templates/svg-symbols.svg) template could serve as a basis.
I should add it to the default template later. 

I would like to keep this module as  dumb as possible, so no conversion of `xlink:href` to `href`
In the same way, I would not like to do any renaming of defs ids in this plugin. You could do it beforehand in a different transformation.

Is this answering all your questions?

**Comment by bluemoehre** [comment]
Hi,
if this won't be automated, I would recommend outputting a warning if multiple files contain same IDs. So users will notice the problem more early. Also giving some hint how to solve the problem (e.g. external plugin) would simplify the usage of this module.

Thanks =)

**Comment by Hiswe** [comment]
@bluemoehre Yes a warning can be done.
Although it will be dump also :) It will check only the ids & not the content of the defs. Is that good for you?

**Comment by bluemoehre** [comment]
@Hiswe Sure. Simply check all IDs which will be added together to `defs` section. Should be enough I think. Thx man.

**Comment by fvsch** [comment]
I made a template that fixes this issue by checking if `xlink:href` occurs in the symbols or defs and outputting a `xmlns:xlink` attribute on the `<svg>` element in that case:
https://github.com/gradientz/assets-builder/blob/master/assets-builder/tasks/svgsymbols-sprite.svg?short_path=5622458
