### ISSUE TITLE
Avoid generating a template with zero icons

### ISSUE THREAD

**Issue by fvsch** [Hiswe/gulp-svg-symbols#38]
If there were no files in a stream, gulp-svg-symbols will still generated the templates and add them to the stream. For instance:

```js
gulp.src('this/path/doesnt/match/any/*.svg')
  .pipe(svgSymbols())
  .pipe(gulp.dest('dist/sprite.svg'))
```

will still generate a `dist/sprite.svg` file, with no symbols.

Would it be possible to return nothing (or an empty-ish stream; sorry if I'm using those concepts wrongly by the way) when the source stream is empty? That's what other gulp plugins I use tend to do.

**Comment by Hiswe** [comment]
You're right :)

Thanks again for all those comments!

**Comment by Hiswe** [comment]
@fvsch done in 3.0
