### ISSUE TITLE
Change id based on file path?

### ISSUE THREAD

**Issue by tomgenoni** [Hiswe/gulp-svg-symbols#41]
I understand I can alter each symbol `id` but is there a way to pass in variable derived from the `file.relative` string? 

```
.pipe(svgSymbols({
  id: path + '-%f'
}))
```

In this example if the svg was in the filesystem as:

```
ui/notification/error.svg
```

I'd like the `symbol` output to be

```
<symbol id="ui-notification-error" ... >
```

**Comment by Hiswe** [comment]
@tomgenoni I should be simply:

```js
.pipe(svgSymbols({
  id:  'ui-notification-%f'
}))
```

**Comment by fvsch** [comment]
You can also use [gulp-rename](https://www.npmjs.com/package/gulp-rename) to rename the files however you like, before using gulp-svg-symbols.

This may feel a bit hackish, but given how gulp plugins work it does make sense IMO. You’re just changing some metadata in a stream.

**Comment by tomgenoni** [comment]
@Hiswe Your example uses a hard-coded variable. What I'm looking for is a way to pass in a variable . I found a solution but it seems overly complicated. 

With each file I'm calling `getFilePath()` which is a custom function that extracts the filename from the stream and assigns it to a global variable `svgFileName`. Ideally the full path would be already available inside `svgSymbols` pipe the to manipulate. 

```
            ...
            .pipe(getFilePath())
            .pipe(
                rename(function(path) {
                    path.basename = 'tp-' + folder + '-' + svgFileName;
                    path.extname = '';
                })
            )
            .pipe(
                svgSymbols({
                    id: '%f',
                    ...
```

This means the symbol code in the sprite for the SVG living at `ui/alert/warning--medium.svg` is:

```
<symbol id="tp-ui-alert-warning--medium" ... >
```

**Comment by fvsch** [comment]
What you did looks simple enough. I'm just not sure why there are two steps (`getFilePath()` and the rename step), and not just one renaming step.

Alternatively, can the `slug` option help?
https://github.com/Hiswe/gulp-svg-symbols#slug
It lets your rewrite the name used in the id attribute however you want; but I don't think it gives you access to the file's path, only to the file's basename.

**Comment by Hiswe** [comment]
@tomgenoni sorry I misread your question.

I think @fvsch solution should be ok
I haven't tested it but it should look like this:

```js
gulp
.src( `icons/**/*.svg` )
.pipe( rename( path => {
  const { basename, dirname } = path
  path.basename = `${dirname.replace('/', '')}-${basename}`
}) )
.pipe( svgSymbols() )

```

**Comment by tomgenoni** [comment]
Thanks @Hiswe! Yes, with a small modification that worked.

**Comment by Hiswe** [comment]
@tomgenoni maybe you can post your solution for further reference and close the ticket :)

**Comment by tomgenoni** [comment]
My changes were trivial. The above solution worked as expected. Thanks again.
