### ISSUE TITLE
#svg-symbols within #svg-symbols wrapper?

### ISSUE THREAD

**Issue by sensaetions** [Hiswe/gulp-svg-symbols#44]
Hello, I'm able to get the `svg-symbols.svg` file created. But when I view the generated file, the first `<symbol>` I see has an ID of `#svg-symbols`. But within that symbol are also multiple symbols inside of it that also shares the same ID. What's going on, why does this happen, and how to fix?

Thanks in advance.

**Comment by Hiswe** [comment]
I think it's because in the `gulp.src` you are **not** omitting the `svg-symbols.svg` file.
So every time you run the script, you embed in the svg-symbols.svg the previous svg-symbols.svg
