### ISSUE TITLE
Multiple sprites?

### ISSUE THREAD

**Issue by sensaetions** [Hiswe/gulp-svg-symbols#45]
I'm trying to create multiple different sprite files. When I pass the svg-symbols task into rename, it only renames the css file. I have specified the specific folder assets that I want to generate as its own sprite. How can I rewrite my gulp task so that the task creates a different svg file and its associated css file, that's separate from the default sprite? Do you have any examples? Thank you in advance.

**Comment by Hiswe** [comment]
Hi,

Using gulp4 and lazypipe to avoid repetitions I will do something like this:


```js
const gulp      = require( 'gulp' )
const $         = require( 'gulp-load-plugins' )()
const lazypipe  = require( 'lazypipe' )

const defaultOptions = {
  id:           'icon-%f',
  className:    '.icon-%f',
  fontSize:     16,
  svgClassname: 'svg-icon-lib',
}

function processIcons( basename, optionsOverride = {} ) {
  const options = Object.assign({}, defaultOptions, optionsOverride)
  return lazypipe()
  .pipe( $.svgSymbols, options )
  .pipe( $.rename, {basename} )
  .pipe( () => $.if( /[.]svg$/, gulp.dest('views')) )
  .pipe( () => $.if( /[.]css$/, gulp.dest('styles')) )
}

// $.util.noop is explained here
// https://stackoverflow.com/questions/40098156/what-about-this-combination-of-gulp-concat-and-lazypipe-is-causing-an-error-usin/40101404#40101404
function uiIcons() {
  return gulp
  .src( 'icons/ui/*.svg' )
  .pipe( processIcons('ui-icons')() )
  .pipe( $.util.noop )
}

function socialIcons() {
  return gulp
  .src( 'icons/socials/*.svg' )
  .pipe( processIcons('social-icons', {
    id:        'social-%f', 
    className: '.social-%f',
  })() )
  .pipe( $.util.noop )
}

const icons = gulp.parallel( uiIcons, socialIcons )
```

Is this what to try to achieve?

**Comment by sensaetions** [comment]
Hello,
I am not familiar with lazypipe and have not used it before. But it appears the idea is similar (creating two (or multiple) separate sprites with different sources and different file names.

Are you familiar with Foundation 6.4? I'm using Foundation 6.4's gulp setup, and am curious if your examples will work in such a framework?

**Comment by Hiswe** [comment]
Lazypipe is really just a way to avoid duplicating code.
But you can just copy and paste your first sprite task and make second one with it with different source and different destination.

I'm not familiar with foundation but gulp is framework agnostic. It relies only on nodejs.
So my example will function if you have the right dependencies installed.
