### ISSUE TITLE
gulp4 alpha3 and vinyl-fs` 3

### ISSUE THREAD

**Issue by jonnitto** [Hiswe/gulp-svg-symbols#46]
If I run your plugin with gulp4 I got following error: Unhandled rejection TypeError: file.isSymbolic is not a function  
It has to do with `vinyl-fs` version 3

**Comment by phated** [comment]
@jonnitto this module is using a **very** out-of-date Vinyl that comes with gulp-util (which has now been deprecated). They need to update to use Vinyl 2.x directly.

**Comment by Hiswe** [comment]
@jonnitto @phated I’ve been using this plugin recently with gulp 4 without any issues. 

But I’ve also seen gulp-plugin deprecation notice on twitter yesterday or 2 days ago, so I will indeed update this as soon as possible :)

Thanks for using this plugin and giving it some feedback!

**Comment by phated** [comment]
@Hiswe There was a new alpha of gulp 4 pushed to the github repository last week. If you update or install with `gulpjs/gulp#4.0`, you'll get the new version that isn't compatible with the old vinyl you are using.

**Comment by Hiswe** [comment]
@jonnitto the branch [gulp-4](https://github.com/Hiswe/gulp-svg-symbols/tree/gulp-4) should be working with the last version of gulp. I will take the opportunity of this new version to clean some tickets also. 

@phated Thanks for your hard work. The transition was very smooth :)

**Comment by Hiswe** [comment]
Done in 3.0

**Comment by phated** [comment]
Awesome!  Thanks @Hiswe
