### ISSUE TITLE
Add svgStyles

### ISSUE THREAD

**Issue by jonnitto** [Hiswe/gulp-svg-symbols#47]
Beside `svgClassname` it would be great to have to option to add inline styles.

**Comment by Hiswe** [comment]
@jonnitto what do you mean? You want to inject a <style> filled with rules inside the SVG file?
If so I think it should be better to add it with gulp-cheerio instead adding complexity to this plugin that I want to keep as dumb as possible :)

**Comment by jonnitto** [comment]
The same handling as svgClassname just as `style` attribute. So that I can add some inline css. Not inside the `svg` tag, I mean the attribute on the `svg` tag itself

**Comment by Hiswe** [comment]
Ok I understand. Related to #37. Can be achieved by a custom template right now.

**Comment by Hiswe** [comment]
@jonnitto It can be done by using the 3.0 and the option 
```js
{
  svgAttrs: {
    style: `position: absolute;`,
  },
}
```
