### ISSUE TITLE
SVG-symbols is stripping out my preserveAspectRatio atributes

### ISSUE THREAD

**Issue by Lefthandmedia** [Hiswe/gulp-svg-symbols#55]
All my `<svg>'`s have an preserveAspectRatio attribute. The are all stripped out in the resulting `<symbol>`. To be clear i doint mean the container SVG but all children `<symbols>`
How can i fix this?
RDG

**Comment by Hiswe** [comment]
Hi :)

the `preserveAspectRatio` should be present in the symbols if you use the default template

I just checked and it works. 

You can test by following those steps:

- clone the repo 
- go the `examples` folder 
- type  the command `npm install && npm run all-build-in` 
- check the files in `examples/ex-aspect-ratio`

You will see the `preserveAspectRatio` attributes on the symbols

Is there something I'm missing?

**Comment by Lefthandmedia** [comment]
Hi, tnx its working now. forgot that SVGmin was running running first.
tnx for the quick reply

**Comment by Hiswe** [comment]
you're welcome :)
