### ISSUE TITLE
svg-symbols viewbox missing

### ISSUE THREAD

**Issue by mrG0bliN** [Hiswe/gulp-svg-symbols#57]
![image](https://user-images.githubusercontent.com/11839238/45298897-8d550c00-b512-11e8-8f77-8915c97b974e.png)
Hello, can you help?
Add function auto-convert if attr missin?!

**Comment by Hiswe** [comment]
@mrG0bliN The plugin raise a warning but fallback to the sizes if there isn't any viewbox.

You can suppress the warning by setting false to the [warn option](https://github.com/Hiswe/gulp-svg-symbols#warn)

Or if you want to add the `viewbox` attribute, it can be done with [gulp-cheerio](https://www.npmjs.com/package/gulp-cheerio) with something like this (untested)

```js
gulp.src(`./icons/*.svg`).pipe(
  cheerio({
    run($, file) {
      const $svg = $(`svg`);
      const viewbox = $svg.attr(`viewbox`);
      if (viewbox) return;
      const width = $svg.attr(`width`).replace(/[^\d*]/, "");
      const height = $svg.attr(`height`).replace(/[^\d*]/, "");
      $svg.attr(`viewbox`, `0 0 ${width} ${height}`);
    },
    parserOptions: {
      xmlMode: true
    }
  })
);
```

**Comment by mrG0bliN** [comment]
@Hiswe Genius !
