### ISSUE TITLE
TypeError: Cannot read property 'attribs' of undefined

### ISSUE THREAD

**Issue by zetareticoli** [Hiswe/gulp-svg-symbols#60]
Hi, here's my code (copy/paste from docs).

```js
function sprites() {
  return gulp
    .src(config.icons.files)
    .pipe(
      svgSymbols({
        // optional: define a global class for every SVG
        svgAttrs: {
          class: 'svg-symbol'
        },
        // optional: customize another class for each SVG
        class: '.svg-symbol--%f',
        // choose the vue template
        templates: ['default-svg'],
      })
    )
    .pipe(gulp.dest(config.icons.dest))
}
exports.sprites = sprites
```

Launching `gulp sprites` it returns the error.

**Comment by Hiswe** [comment]
@zetareticoli do you have some SVG samples?

**Comment by zetareticoli** [comment]
Something like this:
`
<svg viewBox="0 0 1024 1024"><path class="path1" d="M605.118 588.915l314.061-351.869c25.405-28.606 18.404-53.41 14.203-62.812s-18.204-31.206-56.411-31.206H369.672C359.07 74.815 300.058 22.404 228.844 22.404c-78.615 0-142.628 64.013-142.628 142.628S150.229 307.66 228.844 307.66c2.601 0 5.401 0 8.402-.2h.8l251.449 281.855c2 2.2 4.201 4.401 6.401 6.401V871.97c0 22.004-15.803 50.21-34.607 61.612l-175.034 21.604c-16.003 9.802-22.604 20.204-19.804 30.606 3.001 10.402 14.003 15.803 32.806 15.803h495.497c18.804 0 29.806-5.401 32.806-15.803s-3.601-20.804-19.804-30.606l-175.034-21.604c-18.804-11.402-34.607-39.808-34.607-61.612V595.316c2.801-2 5.001-4.001 7.001-6.401zm-306.66-320.263l-49.01-54.811h595.916l-49.01 54.811H298.457zm248.849 149.03c0-30.606 24.805-55.411 55.411-55.411s55.411 24.805 55.411 55.411-24.805 55.411-55.411 55.411-55.411-24.805-55.411-55.411z"/></svg>
`

**Comment by Hiswe** [comment]
@zetareticoli just tested it and found no problems.
Can you please provide the stack trace?

**Comment by DSteinmann** [comment]
I just stumbled upon this and in my case, one of the SVGs was empty (no idea why). What helped my narrow it down was piping gulp-debug between src and svgSymbols to find out what svg causes the problem.

**Comment by zetareticoli** [comment]
The problem was an empty .svg files. 

Thank you

**Comment by the-sides** [comment]
This was my problem too. Thanks for clearly pointing this out.
